//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebInstitoTurismo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EMPRESA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPRESA()
        {
            this.CATALOGO_HOTEL = new HashSet<CATALOGO_HOTEL>();
            this.EMPRESA_RESTAURANTE = new HashSet<EMPRESA_RESTAURANTE>();
            this.FOTO_EMPRESA = new HashSet<FOTO_EMPRESA>();
            this.MUSEO = new HashSet<MUSEO>();
            this.RECORRIDO_EMPRESA = new HashSet<RECORRIDO_EMPRESA>();
        }
    
        public int ID { get; set; }
        [Required(ErrorMessage = "campo obligatorio")]
        public string NOMBRE { get; set; }
        [Required(ErrorMessage = "campo obligatorio")]
        public string DIRECCION { get; set; }
        [Required(ErrorMessage = "campo obligatorio")]
        public string TELEFONO { get; set; }
        [EmailAddress(ErrorMessage = "Ingrese un correo valido")]
        public string CORREO { get; set; }
        public Nullable<bool> ESTADO { get; set; }
        public Nullable<bool> APROBADO { get; set; }
        public Nullable<int> ID_TIPO { get; set; }
        public Nullable<int> ID_REGION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CATALOGO_HOTEL> CATALOGO_HOTEL { get; set; }
        public virtual REGION REGION { get; set; }
        public virtual TIPO_EMPRESA TIPO_EMPRESA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPRESA_RESTAURANTE> EMPRESA_RESTAURANTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FOTO_EMPRESA> FOTO_EMPRESA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MUSEO> MUSEO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECORRIDO_EMPRESA> RECORRIDO_EMPRESA { get; set; }
    }
}
