//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebInstitoTurismo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class INSTITUTO_DE_TURISMOEntities : DbContext
    {
        public INSTITUTO_DE_TURISMOEntities()
            : base("name=INSTITUTO_DE_TURISMOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMINISTRADOR> ADMINISTRADOR { get; set; }
        public virtual DbSet<CATALOGO_HOTEL> CATALOGO_HOTEL { get; set; }
        public virtual DbSet<CATALOGO_RESTAURANTE> CATALOGO_RESTAURANTE { get; set; }
        public virtual DbSet<EMPRESA> EMPRESA { get; set; }
        public virtual DbSet<EMPRESA_RESTAURANTE> EMPRESA_RESTAURANTE { get; set; }
        public virtual DbSet<ESPECIALIDAD> ESPECIALIDAD { get; set; }
        public virtual DbSet<FOTO_EMPRESA> FOTO_EMPRESA { get; set; }
        public virtual DbSet<MUSEO> MUSEO { get; set; }
        public virtual DbSet<RECORRIDO> RECORRIDO { get; set; }
        public virtual DbSet<RECORRIDO_EMPRESA> RECORRIDO_EMPRESA { get; set; }
        public virtual DbSet<REGION> REGION { get; set; }
        public virtual DbSet<ROL> ROL { get; set; }
        public virtual DbSet<SERVICIO> SERVICIO { get; set; }
        public virtual DbSet<SITIO_TURISTICO> SITIO_TURISTICO { get; set; }
        public virtual DbSet<TIPO_EMPRESA> TIPO_EMPRESA { get; set; }
        public virtual DbSet<FOTO_SITIO> FOTO_SITIO { get; set; }
    }
}
