//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebInstitoTurismo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECORRIDO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RECORRIDO()
        {
            this.RECORRIDO_EMPRESA = new HashSet<RECORRIDO_EMPRESA>();
        }
    
        public int ID { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<System.DateTime> FECHA_I { get; set; }
        public Nullable<System.DateTime> FECHA_F { get; set; }
        public string DPI { get; set; }
    
        public virtual ADMINISTRADOR ADMINISTRADOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECORRIDO_EMPRESA> RECORRIDO_EMPRESA { get; set; }
    }
}
