//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebInstitoTurismo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SITIO_TURISTICO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SITIO_TURISTICO()
        {
            this.FOTO_SITIO = new HashSet<FOTO_SITIO>();
        }
    
        public int ID { get; set; }
        [Required(ErrorMessage = "Campo obligatorio")]
        public string NOMBRE { get; set; }
        public string DIRECCION { get; set; }
        [Required(ErrorMessage = "Campo obligatorio")]
        public Nullable<int> ID_REGION { get; set; }
    
        public virtual REGION REGION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FOTO_SITIO> FOTO_SITIO { get; set; }
    }
}
