CREATE DATABASE INSTITUTO_DE_TURISMO
GO
USE INSTITUTO_DE_TURISMO
GO
CREATE TABLE ROL(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	TIPO VARCHAR(30) 
)
GO
CREATE TABLE ADMINISTRADOR(
	DPI VARCHAR (50) PRIMARY KEY,
	NOMBRE VARCHAR (50),
	EMAIL VARCHAR(50),
	TELEFONO VARCHAR(50),
	PASS VARBINARY(MAX) NOT NULL,
	ID_ROL INT FOREIGN KEY (ID_ROL) REFERENCES ROL(ID)
)
GO
CREATE TABLE REGION(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	NOMBRE VARCHAR(50)
)
GO
CREATE TABLE SITIO_TURISTICO(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	NOMBRE VARCHAR(50) NOT NULL,
	DIRECCION VARCHAR(255), 
	ID_REGION INT FOREIGN KEY (ID_REGION) REFERENCES REGION(ID)
)
GO

CREATE TABLE FOTO_SITIO(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	DIRECCION VARBINARY(MAX) NOT NULL,
	TITULO VARCHAR(50),
	ID_SITIO INT FOREIGN KEY(ID_SITIO) REFERENCES SITIO_TURISTICO(ID)
)
GO

CREATE TABLE TIPO_EMPRESA(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	TIPO VARCHAR(50)
)
GO

CREATE TABLE EMPRESA(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	NOMBRE VARCHAR(50) NOT NULL,
	DIRECCION VARCHAR(255),
	TELEFONO VARCHAR(50),
	CORREO VARCHAR(50),
	ESTADO BIT DEFAULT 0,
	APROBADO BIT DEFAULT 0,
	ID_TIPO INT FOREIGN KEY (ID_TIPO) REFERENCES TIPO_EMPRESA(ID),
	ID_REGION INT FOREIGN KEY (ID_REGION) REFERENCES REGION(ID)
)
GO

CREATE TABLE FOTO_EMPRESA(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	DIRECCION VARCHAR(255),
	TITULO VARCHAR(50),
	ID_EMPRESA INT FOREIGN KEY(ID_EMPRESA) REFERENCES EMPRESA(ID)
)
GO

CREATE TABLE EMPRESA_RESTAURANTE(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	HORA_I TIME,
	HORA_F TIME,
	ID_EMPRESA INT FOREIGN KEY(ID_EMPRESA) REFERENCES EMPRESA(ID)
)
GO

CREATE TABLE ESPECIALIDAD(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	DESCRIPCION VARCHAR(255)
)
GO

CREATE TABLE CATALOGO_RESTAURANTE(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	VALIDACION BIT DEFAULT 0,
	ID_RESTAURANTE INT FOREIGN KEY (ID_RESTAURANTE) REFERENCES EMPRESA_RESTAURANTE(ID),
	ID_ESPECIALIDAD INT FOREIGN KEY(ID_ESPECIALIDAD) REFERENCES ESPECIALIDAD(ID)
)
GO

CREATE TABLE SERVICIO(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	DESCRIPCION VARCHAR(255)
)
GO

CREATE TABLE CATALOGO_HOTEL(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	VALIDACION BIT DEFAULT 0,
	ID_SERVICIO INT FOREIGN KEY(ID_SERVICIO) REFERENCES SERVICIO(ID),
	ID_EMPRESA INT FOREIGN KEY(ID_EMPRESA) REFERENCES EMPRESA(ID)
)
GO



CREATE TABLE MUSEO(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	HORA_INICIO TIME,
	HORA_FIN TIME,
	TARIFA VARCHAR(50),
	ID_EMPRESA INT FOREIGN KEY(ID_EMPRESA) REFERENCES EMPRESA(ID)
)
GO

CREATE TABLE RECORRIDO(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	NOMBRE VARCHAR(50),
	FECHA_I DATETIME,
	FECHA_F DATETIME,
	DPI VARCHAR(50) FOREIGN KEY(DPI) REFERENCES ADMINISTRADOR(DPI) 	
)
GO

CREATE TABLE RECORRIDO_EMPRESA(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	ID_RECORRIDO INT FOREIGN KEY(ID_RECORRIDO) REFERENCES RECORRIDO(ID),
	ID_EMPRESA INT FOREIGN KEY(ID_EMPRESA) REFERENCES EMPRESA(ID) 
)
GO

CREATE TABLE MEGUSTA_EMPRESA(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	FECHA DATETIME DEFAULT CURRENT_TIMESTAMP,
	DPI VARCHAR(50) FOREIGN KEY(DPI) REFERENCES ADMINISTRADOR(DPI),
	ID_EMPRESA INT FOREIGN KEY(ID_EMPRESA) REFERENCES EMPRESA(ID)
)

CREATE TABLE FAVORITO_EMPRESA(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	FECHA DATETIME DEFAULT CURRENT_TIMESTAMP,
	DPI VARCHAR(50) FOREIGN KEY(DPI) REFERENCES ADMINISTRADOR(DPI),
	ID_EMPRESA INT FOREIGN KEY(ID_EMPRESA) REFERENCES EMPRESA(ID)
)

CREATE TABLE COMENTARIO_EMPRESA
(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	FECHA DATETIME DEFAULT CURRENT_TIMESTAMP,
	COMENT VARCHAR(255) NOT NULL,  
	DPI VARCHAR(50) FOREIGN KEY(DPI) REFERENCES ADMINISTRADOR(DPI),
	ID_EMPRESA INT FOREIGN KEY(ID_EMPRESA) REFERENCES EMPRESA(ID)
)

CREATE TABLE COMPARTIR_EMPRESA(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	FECHA DATETIME DEFAULT CURRENT_TIMESTAMP,
	EMISOR VARCHAR(50) FOREIGN KEY(EMISOR) REFERENCES ADMINISTRADOR(DPI),
	DESTINATARIO VARCHAR(50) FOREIGN KEY(DESTINATARIO) REFERENCES ADMINISTRADOR(DPI),
	ID_EMPRESA INT FOREIGN KEY(ID_EMPRESA) REFERENCES EMPRESA(ID)	
)

CREATE TABLE MEGUSTA_SITIO(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	FECHA DATETIME DEFAULT CURRENT_TIMESTAMP,
	DPI VARCHAR(50) FOREIGN KEY(DPI) REFERENCES ADMINISTRADOR(DPI),
	ID_SITIO INT FOREIGN KEY(ID_SITIO) REFERENCES SITIO_TURISTICO(ID)
)

CREATE TABLE FAVORITO_SITIO(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	FECHA DATETIME DEFAULT CURRENT_TIMESTAMP,
	DPI VARCHAR(50) FOREIGN KEY(DPI) REFERENCES ADMINISTRADOR(DPI),
	ID_SITIO INT FOREIGN KEY(ID_SITIO) REFERENCES SITIO_TURISTICO(ID)
)

CREATE TABLE COMENTARIO_SITIO
(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	FECHA DATETIME DEFAULT CURRENT_TIMESTAMP,
	COMENT VARCHAR(255) NOT NULL,  
	DPI VARCHAR(50) FOREIGN KEY(DPI) REFERENCES ADMINISTRADOR(DPI),
	ID_SITIO INT FOREIGN KEY(ID_SITIO) REFERENCES SITIO_TURISTICO(ID)
)

CREATE TABLE COMPARTIR_SITIO(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	FECHA DATETIME DEFAULT CURRENT_TIMESTAMP,
	EMISOR VARCHAR(50) FOREIGN KEY(EMISOR) REFERENCES ADMINISTRADOR(DPI),
	DESTINATARIO VARCHAR(50) FOREIGN KEY(DESTINATARIO) REFERENCES ADMINISTRADOR(DPI),
	ID_SITIO INT FOREIGN KEY(ID_SITIO) REFERENCES SITIO_TURISTICO(ID)	
)

USE INSTITUTO_DE_TURISMO

SELECT *FROM COMENTARIO_EMPRESA